'use client';
import React, { useState } from 'react';
import { Card, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { t } from '@/lib/i18n';
import { HumanRecommendation } from '@/lib/transforms/recommendations';
interface RecommendationCardProps { recommendation: HumanRecommendation; onSimulate: (id: string) => Promise<void>; onApply: (id: string) => Promise<void>; onReject: (id: string) => Promise<void>; safetyBlocked: boolean; safetyMessage?: string; }
const riskColors = { low: 'text-emerald-600', medium: 'text-amber-600', high: 'text-red-600' };
const riskDots = { low: 'bg-emerald-500', medium: 'bg-amber-500', high: 'bg-red-500' };
export function RecommendationCard({ recommendation: reco, onSimulate, onApply, onReject, safetyBlocked, safetyMessage }: RecommendationCardProps) {
  const [loading, setLoading] = useState<'simulate' | 'apply' | 'reject' | null>(null);
  const handleAction = async (action: 'simulate' | 'apply' | 'reject', fn: (id: string) => Promise<void>) => { setLoading(action); try { await fn(reco.id); } finally { setLoading(null); } };
  return (<Card className="border-l-4 border-l-brand-500"><CardContent><div className="flex items-start gap-2 mb-3"><span className="text-lg">{'💡'}</span><h4 className="text-base font-semibold text-slate-900">{reco.title}</h4></div><div className="mb-3"><p className="text-xs font-medium text-slate-500 uppercase tracking-wide mb-1">{t('recommendations.why')}</p><p className="text-sm text-slate-700">{reco.why}</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4"><div className="bg-emerald-50 rounded-lg p-3"><p className="text-xs font-medium text-emerald-600 mb-1">{t('recommendations.impact')}</p><p className="text-sm text-emerald-800">{reco.impact}</p></div><div className="bg-slate-50 rounded-lg p-3"><p className="text-xs font-medium text-slate-500 mb-1">{t('recommendations.risk')}</p><div className="flex items-center gap-1.5"><span className={`w-2 h-2 rounded-full ${riskDots[reco.riskLevel]}`} /><p className={`text-sm ${riskColors[reco.riskLevel]}`}>{reco.risk}</p></div></div></div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" loading={loading === 'simulate'} onClick={() => handleAction('simulate', onSimulate)}>{t('recommendations.simulate')}</Button><div className="relative group"><Button variant="primary" size="sm" disabled={safetyBlocked} loading={loading === 'apply'} onClick={() => handleAction('apply', onApply)}>{t('recommendations.apply')}</Button>{safetyBlocked && safetyMessage && (<div className="absolute bottom-full left-0 mb-2 px-3 py-1.5 bg-slate-800 text-white text-xs rounded-lg opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none z-10">{safetyMessage}</div>)}</div><Button variant="ghost" size="sm" loading={loading === 'reject'} onClick={() => handleAction('reject', onReject)}>{t('recommendations.reject')}</Button></div></CardContent></Card>);
}
